const questions = [
  "1. Write a JavaScript statement that creates a variable named name and stores the value 'John'.",
  "2. Write a JavaScript statement that creates a variable named age and stores the number 25.",
  "3. Write code to create a constant named PI and assign the value 3.14.",
  "4. Write code to declare a variable using let and assign the value 'JavaScript'.",
  "5. Write a program that prints 'Hello World' to the console.",
  "6. Write code to create a variable named city and assign 'Mumbai'.",
  "7. Write code to create two variables, firstName and lastName, and assign values to both.",
  "8. Write code to create a variable named isReady and assign true.",
  "9. Write code to create a variable named discount and assign 15.",
  "10. Write code to create a variable named result and assign 5 + 7.",
  "11. Write code to create a variable named totalCost and assign the result of 100 * 2.",
  "12. Write code to create a variable named text and assign '  welcome  ', then trim it.",
  "13. Write code to create a variable named myName and assign 'Alice', then print it in uppercase.",
  "14. Write code to create a variable named password and check if it is empty. Print 'Missing password' if true.",
  "15. Write code to create a variable named count and assign 0, then increase it by 1 using ++.",
  "16. Write code that adds 10 and 20 and stores the result in a variable named total.",
  "17. Write code that subtracts 5 from 15 and logs the result.",
  "18. Write code that multiplies 7 and 6 and stores the result in a variable named product.",
  "19. Write code that divides 30 by 5 and prints the result.",
  "20. Write code that finds the remainder of 17 divided by 5 and stores it in a variable named remainder.",
  "21. Write code that uses the + operator to add two numbers and print the result.",
  "22. Write code that uses the * operator to multiply two numbers and print the result.",
  "23. Write code that uses the % operator to find the remainder of 25 divided by 4.",
  "24. Write code that compares 5 and '5' using === and logs the result.",
  "25. Write code that compares 10 and 10 using == and logs the result.",
  "26. Write code that checks whether 7 is not equal to 9 and logs the result.",
  "27. Write code that checks whether 12 is greater than 8.",
  "28. Write code that checks whether 3 is less than 10.",
  "29. Write code that checks whether a variable named score is greater than or equal to 90.",
  "30. Write code that checks whether isReady is true and prints 'Ready'.",
  "31. Write code that joins two strings, 'Hello' and 'World', and stores the result in a variable.",
  "32. Write code that concatenates 'I am' and ' learning JavaScript'.",
  "33. Write code to create a string variable named message and assign 'JavaScript is fun'.",
  "34. Write code to convert the string '123' into a number and store it in a variable named value.",
  "35. Write code to convert the number 42 into a string and store it in a variable named text.",
  "36. Write code to convert a number to a string using String() and log the result.",
  "37. Write code to convert a string to a number using Number() and log the result.",
  "38. Write code to create a string named email and convert it to uppercase.",
  "39. Write code to convert the string 'HELLO' to lowercase.",
  "40. Write code to remove spaces from both ends of the string '   JavaScript   '.",
  "41. Write code to get the length of the string 'JavaScript'.",
  "42. Write code to split the string 'apple,banana,mango' into an array using a comma.",
  "43. Write code to create a variable named x and assign 5, then increase it by 1.",
  "44. Write code to create a variable named y and assign 10, then decrease it by 2.",
  "45. Write code to check if a value is truthy and print 'Truthy'.",
  "46. Write code to check if a value is falsy and print 'Falsy'.",
  "47. Write code that uses an if statement to print 'Pass' if score is greater than or equal to 50.",
  "48. Write code that uses an if statement to print 'Fail' if marks are less than 40.",
  "49. Write code that checks if a variable named age is greater than 18 and prints 'Adult'.",
  "50. Write code that checks if a variable named number is even. Print 'Even' if true, otherwise print 'Odd'.",
  "51. Write code that uses an else statement to print 'Good Morning' or 'Good Evening' based on time.",
  "52. Write code using else if to print 'Low', 'Medium', or 'High' based on a score value.",
  "53. Write code to create a function named isAdult that checks if a person is 18 or older and returns true or false.",
  "54. Write code to create a function named checkLogin that returns true if a username is not empty.",
  "55. Write code that uses a switch statement to print the day name for a value from 1 to 7.",
  "56. Write code that creates a function named isEven that takes a number and returns true if the number is even.",
  "57. Write code to create a function named isPositive that returns true if a number is greater than 0.",
  "58. Write code to create a variable named score and assign 7, then use a ternary operator to print 'Pass' or 'Fail'.",
  "59. Write code that checks if a variable named age is greater than 18 and prints 'Adult'.",
  "60. Write code to create a function named greetUser that takes a user name and returns 'Hello, ' + user name.",
  "61. Write code to print numbers from 1 to 5 using a for loop.",
  "62. Write code to print even numbers from 2 to 10 using a for loop.",
  "63. Write code to print the numbers from 10 down to 1 using a for loop.",
  "64. Write code to loop through an array named fruits and print each value.",
  "65. Write code to print the first 5 numbers using a while loop.",
  "66. Write code to count from 1 to 3 using a while loop and print each value.",
  "67. Write code to create a for loop that runs 5 times and prints the current value.",
  "68. Write code to create a function named maxNum and returns the larger of two numbers.",
  "69. Write code that creates a function named minNum and returns the smaller of two numbers.",
  "70. Write code to create a function named average that takes three numbers and returns their average.",
  "71. Write code to create a function named getDouble that takes a number and returns the number multiplied by 2.",
  "72. Write code to create a function named fullName that takes first and last names and returns the full name.",
  "73. Write code to create a function named square that takes a number and returns its square.",
  "74. Write code to create a function named add that takes two numbers and returns their sum.",
  "75. Write code to create a function named multiply that takes two numbers and returns their product.",
  "76. Write code to create an array named fruits with three values: 'apple', 'banana', and 'mango'.",
  "77. Write code to create an empty array named numbers.",
  "78. Write code to create an object named student with properties name, age, and grade.",
  "79. Write code to create an empty object named profile.",
  "80. Write code to access the first item in an array named fruits.",
  "81. Write code to access the second item in an array named colors.",
  "82. Write code to access the name property from an object named student.",
  "83. Write code to change the age property of a student object to 21.",
  "84. Write code to add the value 'orange' to the end of an array named fruits.",
  "85. Write code to remove the last item from an array named fruits.",
  "86. Write code to add 'grape' to the beginning of an array named fruits.",
  "87. Write code to remove the first item from an array named fruits.",
  "88. Write code to log the length of an array named fruits.",
  "89. Write code to create an array named names with four names and print the third value.",
  "90. Write code to create an object named car with properties brand, model, and year.",
  "91. Write a function named greet that prints 'Welcome!'.",
  "92. Write code that calls the greet function.",
  "93. Write code that calls the add function with the values 4 and 6.",
  "94. Write a function named sayHi that takes a name and prints 'Hi, ' followed by the name.",
  "95. Write code to create a function named getDouble that takes a number and returns the number multiplied by 2.",
  "96. Write code to create a function named average that takes three numbers and returns their average.",
  "97. Write code to create a function named fullName that takes first and last names and returns the full name.",
  "98. Write code to create a function named maxNum and returns the larger of two numbers.",
  "99. Write code to create a function named minNum and returns the smaller of two numbers.",
  "100. Write a JavaScript program that stores a student's name, age, and grade in an object and prints the object to the console."
];

module.exports = questions;
